version: '3.8'

services:

  # Frontend service - ANGULAR
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network


  # Backend service - NODEJS
  backend:
    build: ./backend
    ports:
      - "5000:5000" 
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mydb
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - app-network


  # Database service - POSTGRES
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network


  # Nginx service - REVERSE PROXY
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - frontend
  #     - backend
  #   networks:
  #     - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
